# Generated by Django 4.2.17 on 2025-01-03 17:19

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
