# Generated by Django 4.2.17 on 2025-01-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
                ('data', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
