# Generated by Django 4.2.17 on 2025-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
