# Generated by Django 4.2.17 on 2025-01-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_verification', '0002_catalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='price',
            new_name='cost',
        ),
    ]
